# Generated by Django 6.0.7 on 2026-08-04 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
