FROM node:alpine AS Frontend
WORKDIR /app
COPY . .

RUN npm i --omit=dev
RUN npm run build

FROM ghcr.io/astral-sh/uv:alpine AS Backend
WORKDIR /app
COPY . .
COPY --from=Frontend /app/dist /app/dist
RUN apk update && apk add libmagic file-dev tzdata
RUN uv sync --no-dev
ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=backend

RUN uv run backend/manage.py collectstatic --noinput

EXPOSE 80

CMD ["uv", "run", "gunicorn", "librebook.wsgi", "--bind", "0.0.0.0:80"]