# Generated by Django 6.0.7 on 2026-08-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='photo',
            field=models.FileField(blank=True, upload_to='books'),
        ),
    ]
