# Generated by Django 6.0.7 on 2026-08-11 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_alter_book_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='count_favorites',
            field=models.IntegerField(default=0),
        ),
    ]
