# Generated by Django 6.0.7 on 2026-08-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_name_alter_user_create_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.EmailField(max_length=254),
        ),
    ]
